#!/bin/bash
# Wrapper for ip6tables-legacy that strips -m comment --comment <value> args
# Required because DSM 6.x kernel (4.4.302) lacks the xt_comment module
cleaned=$(echo "$@" | sed 's/-m comment --comment [^-]*//')
exec /usr/sbin/ip6tables-legacy $cleaned
